name: RAK Creations Landing Zone Deployment
on: workflow_dispatch
jobs:
  Core:
    name: core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: 'LandingZone-GitHubAction-WorkFlow'
      - name: Change to Core Directory
        run: cd ./Core
      
