name: RAK Creations Landing Zone Deployment
on: workflow_dispatch
env:
      TF_VAR_agent_client_id: ${{ secrets.CLIENT_ID }}
      TF_VAR_agent_client_secret: ${{ secrets.CLIENT_SECRET }}
      TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}
      TF_VAR_resource_group_name: rg-terraform-dev-we-01
      TF_VAR_storage_account_name: stoterraformdevwe432
      TF_VAR_container_name: tfstate
jobs:
  Core:
    name: core
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./Core
    env:
      TF_VAR_key: core.tfvars
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: master
      - name: az login
        run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --t ${{ secrets.TENANT_ID }}
      - name: simple az command check
        run: az account show
      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=rg-terraform-dev-we-01" -backend-config="storage_account_name=stoterraformdevwe432" -backend-config="container_name=tfstate"  -backend-config="key=core.tfstate"
      - name: Terraform Plan
        run: terraform plan
      
