name: RAK Creations Landing Zone Deployment
on: workflow_dispatch
jobs:
  Core:
    name: core
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./Core
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: LandingZone-GitHubAction-WorkFlow
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      
