name: RAK Creations Landing Zone Deployment
on: 
      workflow_dispatch:

jobs:
  Core-Plan:
    uses: ./.github/workflows/landingzone-plan.yml
    with:
      container_name: tfstate
      key: core.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Core
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      
  Core-Apply:
    needs: Core-Plan
    if: needs.Core-Plan.result == 'success'
    uses: ./.github/workflows/landingzone-apply.yml
    with:
      container_name: tfstate
      key: core.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Core
      environment: Core Apply
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  Core-Destroy:
    needs: Core-Plan
    if: needs.Core-Plan.result == 'success'
    uses: ./.github/workflows/landingzone-destroy.yml
    with:
      container_name: tfstate
      key: core.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Core
      environment: Core Destroy
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  Networking-Plan:
    needs: Core-Apply
    if: needs.Core-Apply.result == 'success'
    uses: ./.github/workflows/landingzone-plan.yml  
    with:
      container_name: tfstate
      key: networking.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Connectivity_Hub_Spoke
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  Networking-Apply:
    needs: Networking-Plan
    if: needs.Networking-Plan.result == 'success'
    uses: ./.github/workflows/landingzone-apply.yml  
    with:
      container_name: tfstate
      key: networking.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Connectivity_Hub_Spoke
      environment: Networking Apply
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  Networking-Destroy:
    needs: Networking-Plan
    if: needs.Networking-Plan.result == 'success'
    uses: ./.github/workflows/landingzone-destroy.yml  
    with:
      container_name: tfstate
      key: networking.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Connectivity_Hub_Spoke
      environment: Networking Destroy
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }} 

  Management-Plan:
    needs: Core-Apply
    if: needs.Core-Apply.result == 'success'
    uses: ./.github/workflows/landingzone-plan.yml  
    with:
      container_name: tfstate
      key: management.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Management
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  Management-Apply:
    needs: Management-Plan
    if: needs.Management-Plan.result == 'success'
    uses: ./.github/workflows/landingzone-apply.yml  
    with:
      container_name: tfstate
      key: management.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Management
      environment: Management Apply
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  Management-Destroy:
    environment: 
      name: Management-Destroy
    needs: Management-Plan
    if: needs.Management-Plan.result == 'success'
    uses: ./.github/workflows/landingzone-destroy.yml  
    with:
      container_name: tfstate
      key: management.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Management
      environment: Management Destroy
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}