name: RAK Creations Landing Zone Deployment
on: workflow_dispatch
jobs:
  Core:
    name: core
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./Core
    env:
      TF_VAR_agent_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      TF_VAR_agent_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: LandingZone-GitHubAction-WorkFlow
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      
