name: RAK Creations Landing Zone Deployment
on: 
      workflow_dispatch:
env:
      TF_VAR_agent_client_id: ${{ secrets.CLIENT_ID }}
      TF_VAR_agent_client_secret: ${{ secrets.CLIENT_SECRET }}
      TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}
jobs:
  Core-Plan:
    uses: ./.github/workflows/landingzone-plan.yml
    with:
      container_name: tfstate
      key: core.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Core
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      
  Core-Apply:
    environment:
      name: Core Apply
    needs: Core-Plan
    if: needs.Core-Plan.result == 'success'
    uses: ./.github/workflows/landingzone-apply.yml
    with:
      container_name: tfstate
      key: core.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Core
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  Core-Destroy:
    environment:
      name: Core Destroy
    needs: Core-Plan
    if: needs.Core-Plan.result == 'success'
    uses: ./.github/workflows/landingzone-destroy.yml
    with:
      container_name: tfstate
      key: core.tfstate
      resource_group_name: rg-terraform-dev-we-01
      working-directory: ./Core
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    
